### ISSUE TITLE
Formatted ELO credit card number evaluates to MAESTRO credit card type

### ISSUE THREAD

**Issue by IrinaKhubelashvi** [braintree/credit-card-type#148]
### General information

- Library version: 9.1.0
- Browser and OS Chrome 105.0.5195.125 (Official Build) (x86_64) on MacOS 12.6 

### Issue description
ELO space-indented card number returns MAESTRO

creditCardType("6362 9700 0045 7013"); // returns MAESTRO

creditCardType("6362970000457013"); // returns ELO

**Comment by hollabaq86** [comment]
👋 @IrinaKhubelashvi thanks for reaching out, we'll try to replicate and come back to you with thoughts/feedback. 

For braintree folks, issue 670

**Comment by SancSalix** [comment]
This has been written up and will get worked on. Investigation reveals the issue is the white space isn't being stripped out when the pattern matching is being done, so while this is still in flight, I recommend scrubbing any non digit characters out of the string you are sending over.

**Comment by cgdibble** [comment]
In reviewing this further, we've gone with updating the docs to clarify the input expectations here. 

Relevant PR: https://github.com/braintree/credit-card-type/pull/149

As we mention in the README, this isn't a validation library so it is expected that card number validation would occur externally. This is the expected use-case. 

The error you have reported is because of how the spaces interfere with the process, but it is otherwise behaving correctly and as expected given the input.

Sanitizing the card number is fairly straight forward, though:
```js
    function normalizeCardNumber(cardNumber) {
      return String(cardNumber).replace(/[^\d]/g, "");
    }
```
