### ISSUE TITLE
Detecting if card is complete when it has multiple lengths

### ISSUE THREAD

**Issue by Noitidart** [braintree/credit-card-type#151]
### General information

- Library version: 9.1.0
- Browser and OS: All

### Issue description

This is more a question please. While detecting a number like `4242 4242 4242 4242` it returns "visa" and possible lengths include 16, 18, and 19. However this number here is complete. Is it possible to somehow detect that this is complete 16 digit number and has no more digits?

Thanks for sharing such an amazing lib!

**Comment by hollabaq86** [comment]
👋 @Noitidart thanks for reaching out! Unfortunately Visa cards can be [more than 16 digits](https://adagetechnologies.com/19-digit-credit-cards-prepare-commerce-site/), which is why you're seeing that behavior. We genuinely don't know if a card number is "complete" at 16 digits for Visa. Hope this helps!

**Comment by Noitidart** [comment]
Thanks for the fast reply! The stripe payment elements are able to detect somehow that the Visa card is complete as it auto focuses the next field. So could this mean its possible to detect completion?

I'll grab a link and update this comment with demo if stripes thing.
