### ISSUE TITLE
Visa does not support 13 ?

### ISSUE THREAD

**Issue by prijuly2000** [braintree/credit-card-type#43]
The library does not support 13 digit visa cards?

**Comment by skunkworks** [comment]
@prijuly2000 To our knowledge, 13-digit Visa cards are no longer in circulation. Please let us know if you've seen one and would like our library to support it.

**Comment by Kryten0807** [comment]
I think you're probably right that there are no more 13-digit Visa cards in circulation, but...

I'm working with a payment gateway which, in it's testing documentation (http://developer.merchante-solutions.com/#/payment-gateway-testing), includes a 13-digit Visa card among the test cases.

I doubt that a 13-digit Visa card will ever come up, but I'm going to hack together a work around so that I don't get surprised when I go through their certification process :stuck_out_tongue_closed_eyes:

**Comment by crookedneighbor** [comment]
@Kryten0807 We're still not going to include 13 digit visas in this library, but you are welcome to fork the repo and make the modification.

**Comment by crookedneighbor** [comment]
v6.2.0 allows you to adjust the configuration for card brands. See https://github.com/braintree/credit-card-type#adding-card-types for documentation.
