### ISSUE TITLE
Incorrect regexps for prefixPattern

### ISSUE THREAD

**Issue by webbie** [braintree/credit-card-type#80]
`prefixPattern` regexps are incorrect for all card types except Visa, they have `$` sign at the end of regexp:
`/^(3|34|37)$/`
`/^(3|3[0689]|30[0-5])$/` 
..

**Comment by crookedneighbor** [comment]
This is intentional.

You'll see that in all those cases, the `exactPattern` regex will take over when it reaches the end of the prefixPattern. [Amex](https://github.com/braintree/framebus/pull/19), [Diner's Club](https://github.com/braintree/credit-card-type/blob/aa6661a0a828229032ec90c684af413a227578c9/index.js#L106).

IE, it's only intended to match the prefix of the card.

Do you see a specific case where it's wrong and is causing the card detection to be incorrect?

**Comment by webbie** [comment]
Ah got it.. actually, I was using these regexs for my custom validation, with full credit card numbers (that is difference, didn't realized your library takes numbers as user types them).
